#!/bin/bash

theme=`readlink -f ~/.base16_theme | rev | cut -d '/' -f1 | rev`
colortest="$HOME/.config/base16-shell/colortest"
export block1="#`$colortest $theme | grep color01 | cut -d ' ' -f3 | uniq`"
export block2="#`$colortest $theme | grep color02 | cut -d ' ' -f3 | uniq`"
export block3="#`$colortest $theme | grep color03 | cut -d ' ' -f3 | uniq`"
export block4="#`$colortest $theme | grep color04 | cut -d ' ' -f3 | uniq`"
export block5="#`$colortest $theme | grep color05 | cut -d ' ' -f3 | uniq`"
export block6="#`$colortest $theme | grep color06 | cut -d ' ' -f3 | uniq`"
export block7="#`$colortest $theme | grep color16 | cut -d ' ' -f3 | uniq`"
export block8="#`$colortest $theme | grep color17 | cut -d ' ' -f3 | uniq`"
