#!/bin/bash

# get info from playerctl
ARTIST=`playerctl --player=spotify metadata xesam:artist`  
SONGTITLE=`playerctl --player=spotify metadata xesam:title`

# get rid of extra information about the song (featuring etc.)
IFS='(' read -ra tmp1 <<< "$SONGTITLE"
IFS='-' read -ra tmp2 <<< "$tmp1"
SONG=$tmp2

INFO="$ARTIST - $SONG"

# only show 30 characters of artist/song info
LENGTH=${#INFO}
if [ $LENGTH -gt 30 ]; then
OUTPUT=${INFO:0:30}
else
OUTPUT=$INFO
fi

echo $OUTPUT

