#!/bin/sh

# Exports border colors according to current colorscheme as evironment variables
source $HOME/.i3/scripts/i3blocks/base16

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1}'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:
exec conky -c $HOME/.i3/conkyrc
