#!/bin/bash

STATUS=`playerctl --player=spotify status`

if [ "$STATUS" == "Playing" ]; then
    echo ""
elif [ "$STATUS" == "Paused" ]; then
    echo ""
elif [ "$STATUS" == "Not available" ]; then
    echo ""
fi
