#!/bin/bash
#
# i3blocks integration with dunst, showing spotify notifications.
# Author: Davíð Guðni Halldórsson <davidgudni@gmail.com>
#
# Put this rule at the end of your ~/.config/dunst/dunstrc:
#
#     [i3blocks-spotify]
#         summary = "*"
#         script = FULL_PATH_OF_THIS_SCRIPT
#
# Add this block in your ~/.i3blocks.conf:
#
#     [spotify]
#     command=THIS_SCRIPT
#     signal=12

if env | grep -q BLOCK_
then # called by i3blocks
  # get info from playerctl
  ARTIST=`playerctl --player=spotify metadata xesam:artist`  
  SONG=`playerctl --player=spotify metadata xesam:title`
  INFO="$ARTIST - $SONG"

  # only show 30 characters of artist/song info
  LENGTH=${#INFO}
  if [ $LENGTH -gt 30 ]; then
    OUTPUT=${INFO:0:30}
  else
    OUTPUT=$INFO
  fi

  echo $OUTPUT
else # called by dunst
  # signal i3blocks that there was a change
  pkill -RTMIN+12 i3blocks
  exit
fi

