#!/bin/bash
main() {
  if [[ -z "$AWS_PROFILE" ]]; then
    echo "AWS credentials not found"
    exit 1
  fi

  CLUSTERS=$(aws ecs list-clusters --region eu-west-1 | jq -r ".clusterArns[]")
  CLUSTER=$(echo "$CLUSTERS" | fzf)
  echo "CLUSTER:   $CLUSTER"

  SERVICES=$(aws ecs list-services --region eu-west-1 --cluster "$CLUSTER" | jq -r ".serviceArns[]")
  SERVICE=$(echo "$SERVICES" | fzf)
  echo "SERVICE:   $SERVICE"

  TASKS=$(aws ecs list-tasks --region eu-west-1 --cluster "$CLUSTER" --service-name "$SERVICE" | jq -r ".taskArns[]")
  TASK=$(echo "$TASKS" | fzf)
  echo "TASK:      $TASK"


  case "$1" in
    exec)
      CONTAINER_STATUS="RUNNING"
      CONTAINERS=$(aws ecs describe-tasks --region eu-west-1 --cluster "$CLUSTER" --tasks "$TASK" | jq -r --arg container_status "$CONTAINER_STATUS" '.tasks[0].containers[] | select(.lastStatus == $container_status) | .name')
      CONTAINER=$(echo "$CONTAINERS" | fzf)
      echo "CONTAINER: $CONTAINER"

      aws ecs execute-command --region eu-west-1 --cluster "$CLUSTER" --container "$CONTAINER" --command "/bin/sh" --interactive --task "$TASK"
      ;;
    list-containers)
      CONTAINERS=$(aws ecs describe-tasks --region eu-west-1 --cluster "$CLUSTER" --tasks "$TASK" | jq '.tasks[0].containers')
      echo "$CONTAINERS"
      ;;
    *)
      echo "dude"
  esac
}

main "$@"

